CREATE TABLE IF NOT EXISTS Customer(
    email VARCHAR(30) PRIMARY KEY NOT NULL,
    password VARCHAR(20) NOT NULL,
    accountType VARCHAR(5) NOT NULL,
    bID VARCHAR(9) CHECK(LENGTH(bID)=9) UNIQUE,
    sID VARCHAR(9) CHECK(LENGTH(sID)=9) UNIQUE
);

CREATE TABLE IF NOT EXISTS Book(
    ISBN VARCHAR(13) PRIMARY KEY NOT NULL,
    title VARCHAR(100) NOT NULL,
    year VARCHAR(4) NOT NULL,
    genre VARCHAR(30) NOT NULL,
    pName VARCHAR(50) NOT NULL,
    aID VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS Publisher(
    email VARCHAR(30) PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL ,
    phoneNum VARCHAR(11) NOT NULL,
    bankDetails VARCHAR(9) NOT NULL,
    addressID VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS Author(
    ID VARCHAR(9) PRIMARY KEY NOT NULL,
    fName VARCHAR(20) NOT NULL,
    lName VARCHAR(20) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Billing_Information(
    ID VARCHAR(9) PRIMARY KEY NOT NULL,
    fName VARCHAR(20) NOT NULL,
    lName VARCHAR(20) NOT NULL,
    cardNumber VARCHAR(16) UNIQUE NOT NULL,
    CVV VARCHAR(3) NOT NULL,
    expieryDate date
);

CREATE TABLE IF NOT EXISTS Shipping_Information(
    ID VARCHAR(9) PRIMARY KEY NOT NULL,
    province VARCHAR(2) NOT NULL,
    city VARCHAR(30) NOT NULL,
    postalCode VARCHAR(6) NOT NULL,
    streetNum VARCHAR(5) NOT NULL,
    streetName VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Order(
    orderNum VARCHAR(9) PRIMARY KEY NOT NULL,
    orderDate date NOT NULL,
    shippingDate date NOT NULL,
    ID VARCHAR(30) NOT NULL,
);

CREATE TABLE IF NOT EXISTS Contains(
    orderNum VARCHAR(9) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    quantity numeric(4, 0)
    PRIMARY KEY(orderNum, ISBN)
);

CREATE TABLE IF NOT EXISTS Cart(
    orderNum VARCHAR(9) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    PRIMARY KEY(orderNum, ISBN)
);